<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPosts($page = 1, $maxperpage = 3){

        $q = $this->_em->createQueryBuilder()
            ->select('post')
            ->from('AppBundle:Post','post')
            ->orderBy('post.published','DESC');

        $q->setFirstResult(($page - 1) * $maxperpage)
            ->setMaxResults($maxperpage);

        return new Paginator($q);
    }

    public function countPosts(){
        $q = $this->_em->createQueryBuilder()
            ->select('count(post)')
            ->from('AppBundle:Post', 'post');

        $count = $q->getQuery()->getSingleScalarResult();

        return $count;
    }
}
