<?php

namespace AppBundle\Repository;

/**
 * TestGenerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestGenerationRepository extends \Doctrine\ORM\EntityRepository
{
}
