<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMgdywxu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMgdywxu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMgdywxu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMgdywxu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMgdywxu\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mgdywxu',
    'container.build_id' => '0187d734',
    'container.build_time' => 1543505240,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMgdywxu');
